///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: src/assets/music/nueva.aks
/// Generation time: mar 03 nov 2020 20:10:14 CET
///

/// Song 'song_menu' metadata macros
#define song_menu_address  0x250
#define song_menu_size     165
#define song_menu_end      0x2f4

/// Song 'song_menu' array declaration
extern void song_menu[song_menu_size];
